project:
  type: website
  resources:
    - "projects/**/*.py"
    - "projects/**/pyproject.toml"
    - "projects/**/uv.lock"
    - "projects/**/*.zip"

website:
  title: "CS 351 · NLP"
  navbar:
    left:
      - href: index.qmd
        text: NLP Course
      - href: logistics.qmd
        text: Logistics
      - href: schedule.qmd
        text: Schedule
      - href: coding-projects.qmd
        text: Coding Projects
      - href: student-projects.qmd
        text: Student Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
